[theme]

# Primary accent for interactive elements
primaryColor = '#F0F8FF'

# Background color for the main content area
backgroundColor = '#2ECC71'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#FAFAFA'

# Color used for almost all text
textColor = '#0F0F0F'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"